mlflow:
  tracking_uri: "http://localhost:5000"  # MLflow server URI

experiment:
  name: "emoji_sd_baseline"
  model_name: "emoji-stable-diffusion"
  save_dir: "models/checkpoints"
  delete_after_mlflow: true
  max_checkpoints: 5
  log_every: 10
  save_every: 100
  validate_every: 200

optimization:
  weight_decay: 0.01