mlflow:
  tracking_uri: "http://localhost:5000"  # MLflow server URI

experiment:
  name: "emoji_sd_baseline"
  model_name: "emoji-stable-diffusion"
  save_dir: "models/checkpoints"
  log_every: 10
  save_every: 50
  validate_every: 100

optimization:
  weight_decay: 0.01